### PR TITLE
Update dependencies and CircleCI Node

### PR DESCRIPTION
**Pull request by Naramsim**
Maybe this will fix the _trailing slash 404_ error. Basically, it updates the dependencies and uses Node 12 for building the function.

### CODE REVIEW

**Review by phalt — COMMENTED** [review]
There a non-production environment we can test this out in, given we think it might be Cloudflare?

**Comment by Naramsim** [comment]
I tested it locally on my PC, but I can come up with a method for deploying it in our staging env. I need to think about it.

**Comment by Naramsim** [comment]
@phalt alright, we have the `staging` environment deployed if we now push the `staging` branch of this repository. I did it just now so you can check everything out here.

Of course, we are not able to spot the _trailing slash 404_ since it's randomic. But at least we can see that the function works well.

**Comment by Naramsim** [comment]
I'm merging, let's see if as of now the errors will vanish.

**Pull request merged**
